# Generated by Django 3.2.8 on 2021-10-22 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartas_Completas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_carta', models.ImageField(blank=True, upload_to='Cartas_Completas')),
            ],
            options={
                'verbose_name': 'Cartas Completas',
                'verbose_name_plural': 'Cartas Completas',
            },
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programadores', models.CharField(choices=[('1', 'Pedro'), ('2', 'Juan'), ('3', 'Carlos'), ('4', 'Juanita'), ('5', 'Antonio'), ('6', 'Carolina'), ('7', 'Manuel')], max_length=50)),
                ('modulo', models.CharField(choices=[('8', 'Nómina'), ('9', 'Facturación'), ('10', 'Recibos'), ('11', 'Comprobante contable'), ('12', 'Usuarios'), ('13', 'Contabilidad')], max_length=50)),
                ('t_error', models.CharField(choices=[('14', '404'), ('15', 'Stack overflow'), ('16', 'Memory out of range'), ('17', 'Null pointer'), ('18', 'Syntax error'), ('19', 'Encoding error')], max_length=50)),
                ('carta_repetida', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'verbose_name': 'Cartas_jugador',
                'verbose_name_plural': 'Cartas jugadores',
            },
        ),
    ]
